const WATCHES = [
  {
    id: 1,
    brand: "Rolex",
    model: "Submariner Date",
    ref: "126610LN",
    image: "https://i.ebayimg.com/images/g/eM4AAOSwBYVmzVSD/s-l1600.jpg",
    price: 10100,
    year: 2020,
    caseDiameter: 41,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 300,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Unidirectional, Cerachrom ceramic (black)",
    lug: 47,
    thickness: 12.5,
    complications: ["Date"],
    category: "Dive",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 2,
    brand: "Rolex",
    model: "Submariner (No Date)",
    ref: "124060",
    image: "https://media.chrono24.com/images/uhren/images-500/rolex-submariner-date-126610ln-2020-gebraucht-34567890.jpg",
    price: 9100,
    year: 2020,
    caseDiameter: 41,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3230",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 300,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Unidirectional, Cerachrom ceramic (black)",
    lug: 47,
    thickness: 12.5,
    complications: [],
    category: "Dive",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 3,
    brand: "Rolex",
    model: "Cosmograph Daytona",
    ref: "116500LN",
    image: "https://img.chrono24.com/images/uhren/38148000-6c3e67d7d2e04e999c0dc1c39cd8a37b-200.jpg",
    price: 15800,
    year: 2016,
    caseDiameter: 40,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 4130",
    powerReserve: 72,
    frequency: 28800,
    jewels: 44,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "White",
    bezel: "Tachymeter, Cerachrom ceramic (black)",
    lug: 48,
    thickness: 12.4,
    complications: ["Chronograph"],
    category: "Chronograph",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 4,
    brand: "Rolex",
    model: "GMT-Master II \"Batman\"",
    ref: "126710BLNR",
    image: "https://cdn.luxurybuys.co.uk/wp-content/uploads/2021/09/126710blnr-1.jpg",
    price: 12150,
    year: 2019,
    caseDiameter: 40,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3285",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Jubilee",
    dial: "Black",
    bezel: "Bidirectional, Cerachrom ceramic (blue/black)",
    lug: 50,
    thickness: 11.7,
    complications: ["Date", "GMT"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 5,
    brand: "Rolex",
    model: "GMT-Master II \"Pepsi\"",
    ref: "126710BLRO",
    image: "https://content.rolex.com/dam/2022/upright-bba-with-shadow/m126710blro-0002.png",
    price: 12150,
    year: 2018,
    caseDiameter: 40,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3285",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Bidirectional, Cerachrom ceramic (blue/red)",
    lug: 50,
    thickness: 11.7,
    complications: ["Date", "GMT"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 6,
    brand: "Rolex",
    model: "Datejust 41",
    ref: "126334",
    image: "https://watchesoff5th.com/cdn/shop/products/Rolex-Datejust-41-Silver-Dial-Stainless-Steel-and-White-Gold-Oyster-Bracelet-Automatic-Mens-Watch-126334-_1.jpg",
    price: 12350,
    year: 2021,
    caseDiameter: 41,
    caseMaterial: "Oystersteel & White Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Silver",
    bezel: "Fluted, white gold",
    lug: 48.4,
    thickness: 12.4,
    complications: ["Date"],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 7,
    brand: "Rolex",
    model: "Datejust 36",
    ref: "126200",
    image: "https://www.bobswatches.com/rolex-blog/wp-content/uploads/2021/09/Rolex-Datejust-36-126200.jpg",
    price: 7650,
    year: 2021,
    caseDiameter: 36,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Silver",
    bezel: "Smooth, Oystersteel",
    lug: 45,
    thickness: 11.7,
    complications: ["Date"],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 8,
    brand: "Rolex",
    model: "Day-Date 40",
    ref: "228238",
    image: "https://swisswatchexpo.com/TheWatchClub/wp-content/uploads/2022/07/Rolex-Day-Date-40-228238-Yellow-Gold-Presidential.jpg",
    price: 38550,
    year: 2015,
    caseDiameter: 40,
    caseMaterial: "18ct Yellow Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3255",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "President",
    dial: "Champagne",
    bezel: "Fluted, 18ct yellow gold",
    lug: 48,
    thickness: 12.4,
    complications: ["Day", "Date"],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 9,
    brand: "Rolex",
    model: "Day-Date 36",
    ref: "128238",
    image: "https://www.bobswatches.com/rolex-blog/wp-content/uploads/2021/08/Day-Date-36-128238-Yellow-Gold.jpg",
    price: 34750,
    year: 2019,
    caseDiameter: 36,
    caseMaterial: "18ct Yellow Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3255",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "President",
    dial: "Champagne",
    bezel: "Fluted, 18ct yellow gold",
    lug: 45,
    thickness: 11.8,
    complications: ["Day", "Date"],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 10,
    brand: "Rolex",
    model: "Explorer",
    ref: "124270",
    image: "https://www.taleda.com/cdn/shop/files/124270_Front.jpg",
    price: 7250,
    year: 2021,
    caseDiameter: 36,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3230",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Smooth, Oystersteel",
    lug: 46,
    thickness: 11.5,
    complications: [],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 11,
    brand: "Rolex",
    model: "Explorer II",
    ref: "226570",
    image: "https://www.bobswatches.com/rolex-blog/wp-content/uploads/2022/09/Rolex-Explorer-II-226570-White-Dial.jpg",
    price: 9800,
    year: 2021,
    caseDiameter: 42,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3285",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "White",
    bezel: "Fixed, 24-hour graduated",
    lug: 50.5,
    thickness: 12.75,
    complications: ["GMT", "Date"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 12,
    brand: "Rolex",
    model: "Sea-Dweller",
    ref: "126600",
    image: "https://dixonwatchco.co.uk/wp-content/uploads/2022/01/Rolex-126600-Sea-Dweller-Single-Red-43mm-2018-Box-Papers.jpg",
    price: 11550,
    year: 2017,
    caseDiameter: 43,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire (with cyclops)",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 1220,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Unidirectional, Cerachrom ceramic (black)",
    lug: 51,
    thickness: 15.5,
    complications: ["Date"],
    category: "Dive",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 13,
    brand: "Rolex",
    model: "Deepsea",
    ref: "136660",
    image: "https://luxurywatchesusa.com/wp-content/uploads/2023/09/Rolex-Deepsea-D-Blue-James-Cameron-136660.jpg",
    price: 14550,
    year: 2023,
    caseDiameter: 44,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire (5mm thick)",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 3900,
    bracelet: "Oyster",
    dial: "D-Blue (gradient)",
    bezel: "Unidirectional, Cerachrom ceramic (black)",
    lug: 52,
    thickness: 17.7,
    complications: ["Date"],
    category: "Dive",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 14,
    brand: "Rolex",
    model: "Yacht-Master 40",
    ref: "126622",
    image: "https://www.bobswatches.com/rolex-blog/wp-content/uploads/2021/08/Yacht-Master-40-126622-Blue-Dial.jpg",
    price: 13350,
    year: 2019,
    caseDiameter: 40,
    caseMaterial: "Oystersteel & Platinum",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Blue",
    bezel: "Bidirectional, platinum",
    lug: 48,
    thickness: 12,
    complications: ["Date"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 15,
    brand: "Rolex",
    model: "Yacht-Master 42",
    ref: "226659",
    image: "https://watchvault.com.au/wp-content/uploads/2022/09/Rolex-Yacht-Master-42-White-Gold-Oysterflex-226659-2022.jpg",
    price: 44650,
    year: 2019,
    caseDiameter: 42,
    caseMaterial: "18ct White Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oysterflex",
    dial: "Blue",
    bezel: "Bidirectional, black rubber",
    lug: 50,
    thickness: 12,
    complications: ["Date"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 16,
    brand: "Rolex",
    model: "Yacht-Master II",
    ref: "116680",
    image: "https://www.bobswatches.com/rolex-blog/wp-content/uploads/2021/08/Yacht-Master-II-116680-White.jpg",
    price: 20800,
    year: 2013,
    caseDiameter: 44,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 4161",
    powerReserve: 72,
    frequency: 28800,
    jewels: 54,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "White",
    bezel: "Bidirectional, programmable countdown",
    lug: 52,
    thickness: 17.3,
    complications: ["Countdown Timer", "Date"],
    category: "Chronograph",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 17,
    brand: "Rolex",
    model: "Sky-Dweller",
    ref: "336934",
    image: "https://www.chronoexpert.com/images/rolex-sky-dweller-336934-black-oysterflex.jpg",
    price: 20550,
    year: 2023,
    caseDiameter: 42,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 9002",
    powerReserve: 72,
    frequency: 28800,
    jewels: 40,
    waterResistance: 100,
    bracelet: "Oysterflex",
    dial: "Black",
    bezel: "Ring Command, fluted",
    lug: 50,
    thickness: 14,
    complications: ["Annual Calendar", "GMT"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 18,
    brand: "Rolex",
    model: "Sky-Dweller",
    ref: "326938",
    image: "https://www.bobswatches.com/rolex-blog/wp-content/uploads/2021/08/Sky-Dweller-326938-White-Gold-Brown.jpg",
    price: 59900,
    year: 2017,
    caseDiameter: 42,
    caseMaterial: "18ct White Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 9002",
    powerReserve: 72,
    frequency: 28800,
    jewels: 40,
    waterResistance: 100,
    bracelet: "Leather",
    dial: "Brown",
    bezel: "Ring Command, smooth white gold",
    lug: 50,
    thickness: 14,
    complications: ["Annual Calendar", "GMT"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 19,
    brand: "Rolex",
    model: "Air-King",
    ref: "126900",
    image: "https://www.bobswatches.com/rolex-blog/wp-content/uploads/2022/04/Rolex-Air-King-126900.jpg",
    price: 7900,
    year: 2022,
    caseDiameter: 40,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3230",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Smooth, Oystersteel",
    lug: 48,
    thickness: 12,
    complications: [],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 20,
    brand: "Rolex",
    model: "Oyster Perpetual 41",
    ref: "124300",
    image: "https://www.bobswatches.com/rolex-blog/wp-content/uploads/2021/08/Oyster-Perpetual-41-124300-Coral-Red.jpg",
    price: 6450,
    year: 2020,
    caseDiameter: 41,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3230",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Coral Red",
    bezel: "Smooth, Oystersteel",
    lug: 48.4,
    thickness: 12.5,
    complications: [],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 21,
    brand: "Rolex",
    model: "Oyster Perpetual 36",
    ref: "126000",
    image: "https://www.bobswatches.com/rolex-blog/wp-content/uploads/2021/08/Oyster-Perpetual-36-126000-Turquoise.jpg",
    price: 5900,
    year: 2020,
    caseDiameter: 36,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3230",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Turquoise Blue",
    bezel: "Smooth, Oystersteel",
    lug: 44.8,
    thickness: 11.8,
    complications: [],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 22,
    brand: "Rolex",
    model: "Lady-Datejust 28",
    ref: "279138RBR",
    image: "https://www.bobswatches.com/rolex-blog/wp-content/uploads/2021/08/Lady-Datejust-28-279138RBR.jpg",
    price: 19750,
    year: 2019,
    caseDiameter: 28,
    caseMaterial: "18ct Yellow Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 2236",
    powerReserve: 55,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Jubilee",
    dial: "Pink",
    bezel: "Diamond-set",
    lug: 34.8,
    thickness: 10.9,
    complications: ["Date"],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 23,
    brand: "Rolex",
    model: "1908",
    ref: "52508",
    image: "https://www.bobswatches.com/rolex-blog/wp-content/uploads/2023/10/Rolex-1908-52508.jpg",
    price: 25000,
    year: 2023,
    caseDiameter: 39,
    caseMaterial: "18ct White Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 7140",
    powerReserve: 66,
    frequency: 21600,
    jewels: 31,
    waterResistance: 50,
    bracelet: "Leather (alligator)",
    dial: "Silver",
    bezel: "Smooth, 18ct white gold",
    lug: 45.5,
    thickness: 9.6,
    complications: [],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 24,
    brand: "Rolex",
    model: "Land-Dweller",
    ref: "m50605rbr",
    image: "https://www.bobswatches.com/rolex-blog/wp-content/uploads/2026/04/rolex-land-dweller-2026.jpg",
    price: 9800,
    year: 2026,
    caseDiameter: 40,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 7135",
    powerReserve: 66,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Smooth, Oystersteel",
    lug: 48,
    thickness: 12,
    complications: [],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
];
