const WATCHES = [
  {
    id: 1,
    brand: "Rolex",
    model: "Submariner Date",
    ref: "126610LN",
    image: "https://images.unsplash.com/photo-1662384197911-e82189f4dc60?w=400&q=80&auto=format&fit=crop",
    price: 10100,
    year: 2020,
    caseDiameter: 41,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 300,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Unidirectional, Cerachrom ceramic (black)",
    lug: 47,
    thickness: 12.5,
    complications: ["Date"],
    category: "Dive",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 2,
    brand: "Rolex",
    model: "Submariner (No Date)",
    ref: "124060",
    image: "https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=400&q=80&auto=format&fit=crop",
    price: 9100,
    year: 2020,
    caseDiameter: 41,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3230",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 300,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Unidirectional, Cerachrom ceramic (black)",
    lug: 47,
    thickness: 12.5,
    complications: [],
    category: "Dive",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 3,
    brand: "Rolex",
    model: "Cosmograph Daytona",
    ref: "116500LN",
    image: "https://images.unsplash.com/photo-1620625515032-6ed0c1790c75?w=400&q=80&auto=format&fit=crop",
    price: 15800,
    year: 2016,
    caseDiameter: 40,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 4130",
    powerReserve: 72,
    frequency: 28800,
    jewels: 44,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "White",
    bezel: "Tachymeter, Cerachrom ceramic (black)",
    lug: 48,
    thickness: 12.4,
    complications: ["Chronograph"],
    category: "Chronograph",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 4,
    brand: "Rolex",
    model: "GMT-Master II \"Batman\"",
    ref: "126710BLNR",
    image: "https://images.unsplash.com/photo-1730757679771-b53e798846cf?w=400&q=80&auto=format&fit=crop",
    price: 12150,
    year: 2019,
    caseDiameter: 40,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3285",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Jubilee",
    dial: "Black",
    bezel: "Bidirectional, Cerachrom ceramic (blue/black)",
    lug: 50,
    thickness: 11.7,
    complications: ["Date", "GMT"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 5,
    brand: "Rolex",
    model: "GMT-Master II \"Pepsi\"",
    ref: "126710BLRO",
    image: "https://images.unsplash.com/photo-1670404160620-a3a86428560e?w=400&q=80&auto=format&fit=crop",
    price: 12150,
    year: 2018,
    caseDiameter: 40,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3285",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Bidirectional, Cerachrom ceramic (blue/red)",
    lug: 50,
    thickness: 11.7,
    complications: ["Date", "GMT"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 6,
    brand: "Rolex",
    model: "Datejust 41",
    ref: "126334",
    image: "https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?w=400&q=80&auto=format&fit=crop",
    price: 12350,
    year: 2021,
    caseDiameter: 41,
    caseMaterial: "Oystersteel & White Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Silver",
    bezel: "Fluted, white gold",
    lug: 48.4,
    thickness: 12.4,
    complications: ["Date"],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 7,
    brand: "Rolex",
    model: "Datejust 36",
    ref: "126200",
    image: "https://images.unsplash.com/photo-1671119720870-df45dcaf81c1?w=400&q=80&auto=format&fit=crop",
    price: 7650,
    year: 2021,
    caseDiameter: 36,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Silver",
    bezel: "Smooth, Oystersteel",
    lug: 45,
    thickness: 11.7,
    complications: ["Date"],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 8,
    brand: "Rolex",
    model: "Day-Date 40",
    ref: "228238",
    image: "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=400&q=80&auto=format&fit=crop",
    price: 38550,
    year: 2015,
    caseDiameter: 40,
    caseMaterial: "18ct Yellow Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3255",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "President",
    dial: "Champagne",
    bezel: "Fluted, 18ct yellow gold",
    lug: 48,
    thickness: 12.4,
    complications: ["Day", "Date"],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 9,
    brand: "Rolex",
    model: "Day-Date 36",
    ref: "128238",
    image: "https://images.unsplash.com/photo-1529168027930-b41c1b3d248b?w=400&q=80&auto=format&fit=crop",
    price: 34750,
    year: 2019,
    caseDiameter: 36,
    caseMaterial: "18ct Yellow Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3255",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "President",
    dial: "Champagne",
    bezel: "Fluted, 18ct yellow gold",
    lug: 45,
    thickness: 11.8,
    complications: ["Day", "Date"],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 10,
    brand: "Rolex",
    model: "Explorer",
    ref: "124270",
    image: "https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&q=80&auto=format&fit=crop",
    price: 7250,
    year: 2021,
    caseDiameter: 36,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3230",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Smooth, Oystersteel",
    lug: 46,
    thickness: 11.5,
    complications: [],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 11,
    brand: "Rolex",
    model: "Explorer II",
    ref: "226570",
    image: "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=400&q=80&auto=format&fit=crop",
    price: 9800,
    year: 2021,
    caseDiameter: 42,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3285",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "White",
    bezel: "Fixed, 24-hour graduated",
    lug: 50.5,
    thickness: 12.75,
    complications: ["GMT", "Date"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 12,
    brand: "Rolex",
    model: "Sea-Dweller",
    ref: "126600",
    image: "https://images.unsplash.com/photo-1637948630380-a0bacf1e6b42?w=400&q=80&auto=format&fit=crop",
    price: 11550,
    year: 2017,
    caseDiameter: 43,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire (with cyclops)",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 1220,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Unidirectional, Cerachrom ceramic (black)",
    lug: 51,
    thickness: 15.5,
    complications: ["Date"],
    category: "Dive",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 13,
    brand: "Rolex",
    model: "Deepsea",
    ref: "136660",
    image: "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=400&q=80&auto=format&fit=crop",
    price: 14550,
    year: 2023,
    caseDiameter: 44,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire (5mm thick)",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 3900,
    bracelet: "Oyster",
    dial: "D-Blue (gradient)",
    bezel: "Unidirectional, Cerachrom ceramic (black)",
    lug: 52,
    thickness: 17.7,
    complications: ["Date"],
    category: "Dive",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 14,
    brand: "Rolex",
    model: "Yacht-Master 40",
    ref: "126622",
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=400&q=80&auto=format&fit=crop",
    price: 13350,
    year: 2019,
    caseDiameter: 40,
    caseMaterial: "Oystersteel & Platinum",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Blue",
    bezel: "Bidirectional, platinum",
    lug: 48,
    thickness: 12,
    complications: ["Date"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 15,
    brand: "Rolex",
    model: "Yacht-Master 42",
    ref: "226659",
    image: "https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=400&q=80&auto=format&fit=crop",
    price: 44650,
    year: 2019,
    caseDiameter: 42,
    caseMaterial: "18ct White Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oysterflex",
    dial: "Blue",
    bezel: "Bidirectional, black rubber",
    lug: 50,
    thickness: 12,
    complications: ["Date"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 16,
    brand: "Rolex",
    model: "Yacht-Master II",
    ref: "116680",
    image: "https://images.unsplash.com/photo-1622434641406-a158123450f9?w=400&q=80&auto=format&fit=crop",
    price: 20800,
    year: 2013,
    caseDiameter: 44,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 4161",
    powerReserve: 72,
    frequency: 28800,
    jewels: 54,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "White",
    bezel: "Bidirectional, programmable countdown",
    lug: 52,
    thickness: 17.3,
    complications: ["Countdown Timer", "Date"],
    category: "Chronograph",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 17,
    brand: "Rolex",
    model: "Sky-Dweller",
    ref: "336934",
    image: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=400&q=80&auto=format&fit=crop",
    price: 20550,
    year: 2023,
    caseDiameter: 42,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 9002",
    powerReserve: 72,
    frequency: 28800,
    jewels: 40,
    waterResistance: 100,
    bracelet: "Oysterflex",
    dial: "Black",
    bezel: "Ring Command, fluted",
    lug: 50,
    thickness: 14,
    complications: ["Annual Calendar", "GMT"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 18,
    brand: "Rolex",
    model: "Sky-Dweller",
    ref: "326938",
    image: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=400&q=80&auto=format&fit=crop",
    price: 59900,
    year: 2017,
    caseDiameter: 42,
    caseMaterial: "18ct White Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 9002",
    powerReserve: 72,
    frequency: 28800,
    jewels: 40,
    waterResistance: 100,
    bracelet: "Leather",
    dial: "Brown",
    bezel: "Ring Command, smooth white gold",
    lug: 50,
    thickness: 14,
    complications: ["Annual Calendar", "GMT"],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 19,
    brand: "Rolex",
    model: "Air-King",
    ref: "126900",
    image: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=400&q=80&auto=format&fit=crop",
    price: 7900,
    year: 2022,
    caseDiameter: 40,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3230",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Smooth, Oystersteel",
    lug: 48,
    thickness: 12,
    complications: [],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 20,
    brand: "Rolex",
    model: "Oyster Perpetual 41",
    ref: "124300",
    image: "https://images.unsplash.com/photo-1585123334904-845d60e97b29?w=400&q=80&auto=format&fit=crop",
    price: 6450,
    year: 2020,
    caseDiameter: 41,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3230",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Coral Red",
    bezel: "Smooth, Oystersteel",
    lug: 48.4,
    thickness: 12.5,
    complications: [],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 21,
    brand: "Rolex",
    model: "Oyster Perpetual 36",
    ref: "126000",
    image: "https://images.unsplash.com/photo-1613468675517-a6b2c6f52286?w=400&q=80&auto=format&fit=crop",
    price: 5900,
    year: 2020,
    caseDiameter: 36,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3230",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Turquoise Blue",
    bezel: "Smooth, Oystersteel",
    lug: 44.8,
    thickness: 11.8,
    complications: [],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 22,
    brand: "Rolex",
    model: "Lady-Datejust 28",
    ref: "279138RBR",
    image: "https://images.unsplash.com/photo-1630329085641-5e86be4a4ee3?w=400&q=80&auto=format&fit=crop",
    price: 19750,
    year: 2019,
    caseDiameter: 28,
    caseMaterial: "18ct Yellow Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 2236",
    powerReserve: 55,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Jubilee",
    dial: "Pink",
    bezel: "Diamond-set",
    lug: 34.8,
    thickness: 10.9,
    complications: ["Date"],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 23,
    brand: "Rolex",
    model: "1908",
    ref: "52508",
    image: "https://images.unsplash.com/photo-1638913972776-873fc7e83a8f?w=400&q=80&auto=format&fit=crop",
    price: 25000,
    year: 2023,
    caseDiameter: 39,
    caseMaterial: "18ct White Gold",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 7140",
    powerReserve: 66,
    frequency: 21600,
    jewels: 31,
    waterResistance: 50,
    bracelet: "Leather (alligator)",
    dial: "Silver",
    bezel: "Smooth, 18ct white gold",
    lug: 45.5,
    thickness: 9.6,
    complications: [],
    category: "Dress",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
  {
    id: 24,
    brand: "Rolex",
    model: "Land-Dweller",
    ref: "m50605rbr",
    image: "https://images.unsplash.com/photo-1602052577122-f73b9710adba?w=400&q=80&auto=format&fit=crop",
    price: 9800,
    year: 2026,
    caseDiameter: 40,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 7135",
    powerReserve: 66,
    frequency: 28800,
    jewels: 31,
    waterResistance: 100,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Smooth, Oystersteel",
    lug: 48,
    thickness: 12,
    complications: [],
    category: "Sport",
    origin: "Switzerland",
    founded: 1905,
    certified: "Superlative Chronometer",
    warranty: "5 years",
  },
];
