const WATCHES = [
  {
    id: 1,
    brand: "Rolex",
    model: "Submariner Date",
    ref: "126610LN",
    image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=400&h=400&fit=crop",
    price: 10550,
    caseDiameter: 41,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 3235",
    powerReserve: 70,
    frequency: 28800,
    jewels: 31,
    waterResistance: 300,
    bracelet: "Oyster",
    dial: "Black",
    bezel: "Unidirectional rotating ceramic",
    lug: 47,
    thickness: 12.5,
    complications: ["Date"],
    category: "Dive",
    origin: "Switzerland",
    founded: 1905,
    certified: "COSC + Rolex",
    warranty: "5 years",
  },
  {
    id: 2,
    brand: "Omega",
    model: "Seamaster Diver 300M",
    ref: "210.30.42.20.01.001",
    image: "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=400&h=400&fit=crop",
    price: 5900,
    caseDiameter: 42,
    caseMaterial: "Stainless Steel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 8800",
    powerReserve: 55,
    frequency: 25200,
    jewels: 35,
    waterResistance: 300,
    bracelet: "Metal Mesh",
    dial: "Black",
    bezel: "Unidirectional rotating ceramic",
    lug: 50,
    thickness: 13.5,
    complications: ["Date"],
    category: "Dive",
    origin: "Switzerland",
    founded: 1848,
    certified: "COSC + METAS",
    warranty: "5 years",
  },
  {
    id: 3,
    brand: "TAG Heuer",
    model: "Carrera Chronograph",
    ref: "CBN2A1B.BA0643",
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=400&h=400&fit=crop",
    price: 5850,
    caseDiameter: 44,
    caseMaterial: "Stainless Steel",
    caseback: "Exhibition",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. Heuer 02",
    powerReserve: 80,
    frequency: 28800,
    jewels: 29,
    waterResistance: 100,
    bracelet: "Leather",
    dial: "Black",
    bezel: "Fixed tachymeter",
    lug: 51,
    thickness: 14.8,
    complications: ["Chronograph", "Date"],
    category: "Chronograph",
    origin: "Switzerland",
    founded: 1860,
    certified: "COSC",
    warranty: "2 years",
  },
  {
    id: 4,
    brand: "Patek Philippe",
    model: "Nautilus",
    ref: "5711/1A-010",
    image: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=400&h=400&fit=crop",
    price: 34835,
    caseDiameter: 40,
    caseMaterial: "Stainless Steel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 26-330 S C",
    powerReserve: 45,
    frequency: 28800,
    jewels: 29,
    waterResistance: 120,
    bracelet: "Integrated Steel",
    dial: "Blue",
    bezel: "Fixed",
    lug: 52,
    thickness: 8.3,
    complications: ["Date"],
    category: "Luxury Sport",
    origin: "Switzerland",
    founded: 1839,
    certified: "Patek Philippe Seal",
    warranty: "2 years",
  },
  {
    id: 5,
    brand: "Audemars Piguet",
    model: "Royal Oak",
    ref: "15500ST.OO.1220ST.01",
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400&h=400&fit=crop",
    price: 32000,
    caseDiameter: 41,
    caseMaterial: "Stainless Steel",
    caseback: "Exhibition",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 4302",
    powerReserve: 70,
    frequency: 28800,
    jewels: 40,
    waterResistance: 50,
    bracelet: "Integrated Steel",
    dial: "Blue",
    bezel: "Fixed octagonal",
    lug: 50,
    thickness: 10.4,
    complications: ["Date"],
    category: "Luxury Sport",
    origin: "Switzerland",
    founded: 1875,
    certified: "AP Manufacture",
    warranty: "2 years",
  },
  {
    id: 6,
    brand: "IWC",
    model: "Portugieser Chronograph",
    ref: "IW371601",
    image: "https://images.unsplash.com/photo-1548171915-e79a6a8bfce9?w=400&h=400&fit=crop",
    price: 7900,
    caseDiameter: 41,
    caseMaterial: "Stainless Steel",
    caseback: "Exhibition",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 69355",
    powerReserve: 46,
    frequency: 28800,
    jewels: 31,
    waterResistance: 30,
    bracelet: "Leather",
    dial: "Silver",
    bezel: "Fixed",
    lug: 52,
    thickness: 11,
    complications: ["Chronograph"],
    category: "Dress",
    origin: "Switzerland",
    founded: 1868,
    certified: "IWC",
    warranty: "2 years",
  },
  {
    id: 7,
    brand: "Seiko",
    model: "Prospex Marinemaster",
    ref: "SBDX001",
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop",
    price: 2100,
    caseDiameter: 44,
    caseMaterial: "Titanium",
    caseback: "Screw-down",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "8L35",
    powerReserve: 50,
    frequency: 21600,
    jewels: 28,
    waterResistance: 300,
    bracelet: "Titanium",
    dial: "Black",
    bezel: "Unidirectional rotating",
    lug: 52,
    thickness: 14.8,
    complications: ["Day", "Date"],
    category: "Dive",
    origin: "Japan",
    founded: 1881,
    certified: "JIS",
    warranty: "3 years",
  },
  {
    id: 8,
    brand: "Grand Seiko",
    model: "Snowflake",
    ref: "SBGA211",
    image: "https://images.unsplash.com/photo-1557531365-e8b22d93dbd0?w=400&h=400&fit=crop",
    price: 5800,
    caseDiameter: 41,
    caseMaterial: "Titanium",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Spring Drive",
    caliber: "9R65",
    powerReserve: 72,
    frequency: 28800,
    jewels: 30,
    waterResistance: 100,
    bracelet: "Titanium",
    dial: "White Textured",
    bezel: "Fixed",
    lug: 46.4,
    thickness: 11.8,
    complications: ["Date"],
    category: "Dress",
    origin: "Japan",
    founded: 1881,
    certified: "Grand Seiko Standard",
    warranty: "3 years",
  },
  {
    id: 9,
    brand: "Cartier",
    model: "Santos de Cartier",
    ref: "WSSA0018",
    image: "https://images.unsplash.com/photo-1622434641406-a158123450f2?w=400&h=400&fit=crop",
    price: 6800,
    caseDiameter: 39.8,
    caseMaterial: "Stainless Steel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. 1847 MC",
    powerReserve: 40,
    frequency: 28800,
    jewels: 23,
    waterResistance: 100,
    bracelet: "Interchangeable Steel",
    dial: "Silver",
    bezel: "Fixed",
    lug: 47.5,
    thickness: 9.08,
    complications: [],
    category: "Dress",
    origin: "France",
    founded: 1847,
    certified: "Cartier",
    warranty: "2 years",
  },
  {
    id: 10,
    brand: "Breitling",
    model: "Navitimer B01",
    ref: "AB0138241G1P1",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=400&h=400&fit=crop",
    price: 9750,
    caseDiameter: 43,
    caseMaterial: "Stainless Steel",
    caseback: "Exhibition",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. B01",
    powerReserve: 70,
    frequency: 28800,
    jewels: 47,
    waterResistance: 30,
    bracelet: "Leather",
    dial: "Black",
    bezel: "Bidirectional slide rule",
    lug: 49,
    thickness: 14.25,
    complications: ["Chronograph", "Slide Rule"],
    category: "Chronograph",
    origin: "Switzerland",
    founded: 1884,
    certified: "COSC",
    warranty: "2 years",
  },
  {
    id: 11,
    brand: "Tudor",
    model: "Black Bay 58",
    ref: "M79030N-0001",
    image: "https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=400&h=400&fit=crop",
    price: 3725,
    caseDiameter: 39,
    caseMaterial: "Oystersteel",
    caseback: "Solid",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "MT5402",
    powerReserve: 70,
    frequency: 28800,
    jewels: 26,
    waterResistance: 200,
    bracelet: "Steel Bracelet",
    dial: "Black",
    bezel: "Unidirectional rotating",
    lug: 47,
    thickness: 11.9,
    complications: [],
    category: "Dive",
    origin: "Switzerland",
    founded: 1926,
    certified: "COSC",
    warranty: "5 years",
  },
  {
    id: 12,
    brand: "Longines",
    model: "Master Collection",
    ref: "L2.793.4.77.3",
    image: "https://images.unsplash.com/photo-1535303311164-664fc9ec6532?w=400&h=400&fit=crop",
    price: 2750,
    caseDiameter: 40,
    caseMaterial: "Stainless Steel",
    caseback: "Exhibition",
    crystal: "Sapphire",
    movement: "Automatic",
    caliber: "Cal. L888",
    powerReserve: 64,
    frequency: 25200,
    jewels: 27,
    waterResistance: 30,
    bracelet: "Leather",
    dial: "Silver",
    bezel: "Fixed",
    lug: 48,
    thickness: 10.15,
    complications: ["Date", "Moonphase"],
    category: "Dress",
    origin: "Switzerland",
    founded: 1832,
    certified: "COSC",
    warranty: "2 years",
  },
];
